/* Generated by Saga 0.47 Virtual-HIL qualification backend 0.48. */
/* Restricted scalar @control_tick subset; no heap/runtime dependency. */
float saga_foc_q_tick(float iq_ref, float iq, float integral_q, float kp, float ki, float resistance, float omega, float ld, float id, float flux, float dt, float limit) {
    float error = (iq_ref - iq);
    float candidate = (integral_q + ((ki * error) * dt));
    float feedforward = ((resistance * iq_ref) + (omega * ((ld * id) + flux)));
    float voltage = (((kp * error) + candidate) + feedforward);
    if ((voltage > limit)) {
        voltage = limit;
    }
    if ((voltage < (-limit))) {
        voltage = (-limit);
    }
    return voltage;
}
