from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
import platform
from pathlib import Path
import sys
import time
import unittest

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def clause_for(test_id: str) -> str:
    name = test_id.lower()
    rules = [
        (("unicode", "bidi", "bom", "crlf"), "5"),
        (("syntax", "numeric_separator", "annotation"), "6"),
        (("source_unit", "project", "lock", "package", "semver"), "7"),
        (("type", "subtyping", "override", "generic", "return", "implicit"), "8"),
        (("identity", "private", "hashable", "equality"), "9"),
        (("decimal", "rational", "integer", "sqrt", "precision", "power", "round", "mean"), "10"),
        (("string", "text", "bytes"), "11"),
        (("list", "map", "set", "collection", "unique", "append"), "12"),
        (("condition", "boolean", "range", "break", "continue", "loop"), "14"),
        (("function", "recursive", "higher_order", "arity"), "15"),
        (("class", "interface", "oop", "reflection"), "16"),
        (("try", "catch", "exception", "overflow", "division", "assert", "bounds"), "17"),
        (("option", "null"), "18"),
        (("task", "parallel", "future", "send"), "19"),
        (("permission", "network", "redirect", "process", "environment", "plugin", "database", "http", "sqlite", "orm", "crypto", "file"), "21"),
        (("diagnostic", "exit_code", "cli"), "22"),
        (("formatter", "linter", "repl", "standardization", "registry"), "23"),
    ]
    for words, clause in rules:
        if any(word in name for word in words):
            return clause
    return "20"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    digest.update(path.read_bytes())
    return digest.hexdigest()


class Result(unittest.TextTestResult):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.started: dict[str, float] = {}
        self.records: list[dict] = []

    def startTest(self, test):
        self.started[test.id()] = time.perf_counter()
        super().startTest(test)

    def _record(self, test, status: str, detail: str = ""):
        test_id = test.id()
        self.records.append({
            "id": test_id,
            "clause": clause_for(test_id),
            "status": status,
            "duration_ms": round((time.perf_counter() - self.started.get(test_id, time.perf_counter())) * 1000, 3),
            "detail": detail,
        })

    def addSuccess(self, test):
        self._record(test, "pass")
        super().addSuccess(test)

    def addFailure(self, test, err):
        self._record(test, "fail", self._exc_info_to_string(err, test))
        super().addFailure(test, err)

    def addError(self, test, err):
        self._record(test, "error", self._exc_info_to_string(err, test))
        super().addError(test, err)

    def addSkip(self, test, reason):
        self._record(test, "skip", reason)
        super().addSkip(test, reason)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="validation/standard-core-conformance-0.17.0.json")
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args()
    suite = unittest.defaultTestLoader.discover(str(ROOT / "tests"))
    stream = open("/dev/null", "w") if args.quiet else sys.stderr
    runner = unittest.TextTestRunner(stream=stream, verbosity=1, resultclass=Result)
    started = time.perf_counter()
    result: Result = runner.run(suite)
    if args.quiet:
        stream.close()
    tests_files = sorted((ROOT / "tests").glob("test_*.py"))
    report = {
        "schema": 1,
        "language": "Saga",
        "language_version": "1.0",
        "implementation": "saga-python 0.17.0",
        "profile": "Standard Core + tested hosted modules",
        "generated_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "host": {"platform": platform.platform(), "python": platform.python_version(), "machine": platform.machine()},
        "suite_files": [{"path": str(p.relative_to(ROOT)), "sha256": sha256(p)} for p in tests_files],
        "records": result.records,
        "summary": {
            "total": result.testsRun,
            "passed": sum(r["status"] == "pass" for r in result.records),
            "failed": len(result.failures),
            "errors": len(result.errors),
            "skipped": len(result.skipped),
            "duration_ms": round((time.perf_counter() - started) * 1000, 3),
            "pass": result.wasSuccessful(),
        },
        "independence_note": "This report is generated by the Saga project and is not an independent laboratory certificate.",
    }
    output = ROOT / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(report["summary"], ensure_ascii=False))
    return 0 if result.wasSuccessful() else 1


if __name__ == "__main__":
    raise SystemExit(main())
