/* Saga C Core 0.18.0
 * Clean-room conformance-oriented implementation of a documented Standard Core subset.
 * It imports/links no Saga Native Go or Saga Python implementation code.
 */
#include <ctype.h>
#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct { int64_t n, d; } Rat;
typedef enum { V_NUM, V_BOOL, V_TEXT, V_LIST } Kind;
typedef struct { Kind k; Rat q; int numeric_style; int b; char text[256]; Rat list[64]; int nlist; } Value;
typedef struct { char name[128]; Value v; int mutable; } Sym;
typedef struct { char name[128], a[64], b[64], expr[256]; } Fn;
static Sym syms[128]; static int nsyms;
static Fn fns[32]; static int nfns;
static const char *diag_id;

static int64_t gcd64(int64_t a,int64_t b){ if(a<0)a=-a;if(b<0)b=-b;while(b){int64_t t=a%b;a=b;b=t;}return a?a:1; }
static Rat rat(int64_t n,int64_t d){ if(!d)d=1;if(d<0){n=-n;d=-d;}int64_t g=gcd64(n,d);Rat q={n/g,d/g};return q; }
static Rat add(Rat a,Rat b){return rat(a.n*b.d+b.n*a.d,a.d*b.d);} 
static Rat divr(Rat a,Rat b){return rat(a.n*b.d,a.d*b.n);} 
static int eqr(Rat a,Rat b){return a.n==b.n&&a.d==b.d;}
static int pow10den(int64_t d){while(d%2==0)d/=2;while(d%5==0)d/=5;return d==1;}
static void print_rat(Rat q){ if(q.d==1){printf("%lld",(long long)q.n);return;} if(pow10den(q.d)){ long double x=(long double)q.n/(long double)q.d; char b[96]; snprintf(b,sizeof(b),"%.18Lf",x); size_t n=strlen(b);while(n&&b[n-1]=='0')b[--n]=0;if(n&&b[n-1]=='.')b[--n]=0;printf("%s",b);return;} printf("%lld/%lld",(long long)q.n,(long long)q.d);}
static const char* skip(const char*s){while(*s&&isspace((unsigned char)*s))s++;return s;}
static void trim(char*s){size_t n=strlen(s);while(n&&isspace((unsigned char)s[n-1]))s[--n]=0;char*p=s;while(*p&&isspace((unsigned char)*p))p++;if(p!=s)memmove(s,p,strlen(p)+1);}
static Sym* find_sym(const char*n){for(int i=nsyms-1;i>=0;i--)if(strcmp(syms[i].name,n)==0)return &syms[i];return NULL;}
static Fn* find_fn(const char*n){for(int i=nfns-1;i>=0;i--)if(strcmp(fns[i].name,n)==0)return &fns[i];return NULL;}
static int ident_char(unsigned char c){return c=='_'||isalnum(c)||c>=0x80;}
static int parse_ident(const char**ps,char*out,size_t cap){const char*s=skip(*ps);size_t n=0;if(!(*s=='_'||isalpha((unsigned char)*s)||(unsigned char)*s>=0x80))return 0;while(*s&&ident_char((unsigned char)*s)){if(n+1<cap)out[n++]=*s;s++;}out[n]=0;*ps=s;return 1;}
static int parse_number(const char**ps,Rat*out){const char*s=skip(*ps);int neg=0;if(*s=='-'){neg=1;s++;}if(!isdigit((unsigned char)*s))return 0;int64_t ip=0;while(isdigit((unsigned char)*s)){ip=ip*10+(*s++-'0');}int64_t den=1,num=ip;if(s[0]=='.'&&isdigit((unsigned char)s[1])){s++;while(isdigit((unsigned char)*s)){num=num*10+(*s++-'0');den*=10;}}if(neg)num=-num;*out=rat(num,den);*ps=s;return 1;}
static Value eval_expr(const char**ps,int*ok);
static Value eval_primary(const char**ps,int*ok){ Value v={0};const char*s=skip(*ps);Rat q;if(parse_number(&s,&q)){v.k=V_NUM;v.q=q;v.numeric_style=(q.d==1?0:1);*ps=s;*ok=1;return v;}if(strncmp(s,"true",4)==0&&!ident_char((unsigned char)s[4])){v.k=V_BOOL;v.b=1;*ps=s+4;*ok=1;return v;}if(strncmp(s,"false",5)==0&&!ident_char((unsigned char)s[5])){v.k=V_BOOL;v.b=0;*ps=s+5;*ok=1;return v;}if(*s=='\"'){s++;size_t n=0;while(*s&&*s!='\"'){if(n+1<sizeof(v.text))v.text[n++]=*s;s++;}if(*s!='\"'){*ok=0;return v;}v.text[n]=0;v.k=V_TEXT;*ps=s+1;*ok=1;return v;}if(*s=='['){s++;v.k=V_LIST;v.nlist=0;for(;;){s=skip(s);if(*s==']'){s++;break;}Rat x;if(!parse_number(&s,&x)||v.nlist>=64){*ok=0;return v;}v.list[v.nlist++]=x;s=skip(s);if(*s==','){s++;continue;}if(*s==']'){s++;break;}*ok=0;return v;}*ps=s;*ok=1;return v;}char name[128];if(parse_ident(&s,name,sizeof(name))){s=skip(s);if(*s=='('){s++;Fn*f=find_fn(name);if(!f){*ok=0;return v;}Value a=eval_expr(&s,ok);if(!*ok)return v;s=skip(s);if(*s++!=','){*ok=0;return v;}Value b=eval_expr(&s,ok);if(!*ok)return v;s=skip(s);if(*s++!=')'){*ok=0;return v;}Sym sa={0},sb={0};strcpy(sa.name,f->a);sa.v=a;strcpy(sb.name,f->b);sb.v=b;int old=nsyms;syms[nsyms++]=sa;syms[nsyms++]=sb;const char*e=f->expr;v=eval_expr(&e,ok);nsyms=old;*ps=s;return v;}Sym*sym=find_sym(name);if(!sym){*ok=0;return v;}v=sym->v;s=skip(s);if(*s=='['){s++;Value idx=eval_expr(&s,ok);if(!*ok||idx.k!=V_NUM||idx.q.d!=1){*ok=0;return v;}s=skip(s);if(*s++!=']'){*ok=0;return v;}int64_t i=idx.q.n;if(v.k!=V_LIST||i<0||i>=v.nlist){diag_id="SAGA-R101";*ok=-1;return v;}v.k=V_NUM;v.q=v.list[i];}*ps=s;*ok=1;return v;}*ok=0;return v;}
static Value eval_div(const char**ps,int*ok){Value v=eval_primary(ps,ok);if(*ok<=0)return v;for(;;){const char*s=skip(*ps);if(*s!='/')break;s++;Value r=eval_primary(&s,ok);if(*ok<=0||v.k!=V_NUM||r.k!=V_NUM||r.q.n==0){*ok=0;return v;}v.q=divr(v.q,r.q);v.numeric_style=2;*ps=s;}return v;}
static Value eval_add(const char**ps,int*ok){Value v=eval_div(ps,ok);if(*ok<=0)return v;for(;;){const char*s=skip(*ps);if(*s!='+')break;s++;Value r=eval_div(&s,ok);if(*ok<=0||v.k!=V_NUM||r.k!=V_NUM){*ok=0;return v;}v.q=add(v.q,r.q);if(v.numeric_style!=2)v.numeric_style=(r.numeric_style==2?2:(v.numeric_style==1||r.numeric_style==1?1:0));*ps=s;}return v;}
static Value eval_expr(const char**ps,int*ok){Value v=eval_add(ps,ok);if(*ok<=0)return v;const char*s=skip(*ps);if(s[0]=='='&&s[1]=='='){s+=2;Value r=eval_add(&s,ok);if(*ok<=0)return v;Value b={.k=V_BOOL};b.b=(v.k==r.k)&&((v.k==V_NUM&&eqr(v.q,r.q))||(v.k==V_BOOL&&v.b==r.b)||(v.k==V_TEXT&&strcmp(v.text,r.text)==0));*ps=s;return b;}return v;}
static void print_value(Value v){switch(v.k){case V_NUM:if(v.numeric_style==2&&v.q.d!=1)printf("%lld/%lld",(long long)v.q.n,(long long)v.q.d);else print_rat(v.q);break;case V_BOOL:printf(v.b?"true":"false");break;case V_TEXT:printf("%s",v.text);break;default:printf("<value>");}}
static int lexical_profile(const unsigned char*s,size_t n){for(size_t i=0;i<n;i++){if(i+2<n&&s[i]==0xE2&&s[i+1]==0x80&&(s[i+2]>=0xAA&&s[i+2]<=0xAE)){diag_id="SAGA-L106";return 0;}if(i+1<n&&s[i]==0xD9&&s[i+1]>=0xA0&&s[i+1]<=0xA9){diag_id="SAGA-L103";return 0;}if(i+1<n&&s[i]==0xCC&&s[i+1]>=0x80){diag_id="SAGA-L105";return 0;}}return 1;}
static int declare_line(const char*line,int execute){int mut=0;const char*s=line;if(strncmp(s,"let ",4)==0)s+=4;else if(strncmp(s,"var ",4)==0){s+=4;mut=1;}else return 0;char name[128];if(!parse_ident(&s,name,sizeof(name)))return -1;s=skip(s);if(*s!='=')return -1;s++;if(!execute){Sym*old=find_sym(name);if(!old){snprintf(syms[nsyms].name,sizeof(syms[nsyms].name),"%s",name);syms[nsyms].mutable=mut;nsyms++;}else old->mutable=mut;return 1;}int ok=0;Value v=eval_expr(&s,&ok);if(ok<=0)return -2;Sym*old=find_sym(name);if(old){old->v=v;old->mutable=mut;}else{snprintf(syms[nsyms].name,sizeof(syms[nsyms].name),"%s",name);syms[nsyms].v=v;syms[nsyms].mutable=mut;nsyms++;}return 1;}
static int check_assignment(const char*line){const char*s=line;char name[128];if(!parse_ident(&s,name,sizeof(name)))return 0;s=skip(s);if(*s!='='||s[1]=='=')return 0;Sym*sym=find_sym(name);if(sym&&!sym->mutable){diag_id="SAGA-T101";return -1;}return 1;}
static int parse_fn(const char*line){if(strncmp(line,"fn ",3)!=0)return 0;const char*s=line+3;Fn f={0};if(!parse_ident(&s,f.name,sizeof(f.name)))return -1;s=skip(s);if(*s++!='(')return -1;if(!parse_ident(&s,f.a,sizeof(f.a)))return -1;const char*comma=strchr(s,',');if(!comma)return -1;s=comma+1;if(!parse_ident(&s,f.b,sizeof(f.b)))return -1;const char*eq=strchr(s,'=');if(!eq)return -1;snprintf(f.expr,sizeof(f.expr),"%s",skip(eq+1));trim(f.expr);fns[nfns++]=f;return 1;}
static int run_print(const char*line){if(strncmp(line,"print(",6)!=0)return 0;const char*s=line+6;int first=1;for(;;){int ok=0;Value v=eval_expr(&s,&ok);if(ok==-1)return -2;if(!ok)return -1;if(!first)printf(" ");print_value(v);first=0;s=skip(s);if(*s==','){s++;continue;}if(*s==')'){printf("\n");return 1;}return -1;}}
static int run_source(char*src,int execute){char*line=strtok(src,"\n");while(line){trim(line);if(!*line){line=strtok(NULL,"\n");continue;}if(strncmp(line,"if ",3)==0){const char*s=line+3;int ok=0;Value v=eval_expr(&s,&ok);if(!ok||v.k!=V_BOOL){diag_id="SAGA-T104";return 4;}}else if(strncmp(line,"fn ",3)==0){if(parse_fn(line)<0)return 3;}else if(strncmp(line,"for ",4)==0){char it[64];const char*s=line+4;if(!parse_ident(&s,it,sizeof(it)))return 3;s=skip(s);if(strncmp(s,"in",2)!=0)return 3;s=skip(s+2);Rat a,b;if(!parse_number(&s,&a)||a.d!=1)return 3;s=skip(s);if(s[0]!='.'||s[1]!='.')return 3;s+=2;if(!parse_number(&s,&b)||b.d!=1)return 3;char*lb=strchr((char*)s,'{'),*rb=strrchr((char*)s,'}');if(!lb||!rb||rb<=lb)return 3;char body[256];size_t bn=(size_t)(rb-lb-1);if(bn>=sizeof(body))return 3;memcpy(body,lb+1,bn);body[bn]=0;trim(body);if(execute){Sym loop={0};snprintf(loop.name,sizeof(loop.name),"%s",it);loop.mutable=0;int64_t step=a.n<=b.n?1:-1;for(int64_t x=a.n;;x+=step){int old=nsyms;loop.v.k=V_NUM;loop.v.q=rat(x,1);syms[nsyms++]=loop;const char*bs=body;char lhs[128];if(!parse_ident(&bs,lhs,sizeof(lhs))){nsyms=old;return 3;}bs=skip(bs);if(*bs++!='='){nsyms=old;return 3;}Sym*target=find_sym(lhs);if(!target||!target->mutable){nsyms=old;diag_id="SAGA-T101";return 4;}int ok=0;Value nv=eval_expr(&bs,&ok);if(!ok){nsyms=old;return 5;}target->v=nv;nsyms=old;if(x==b.n)break;}}}else{int d=declare_line(line,execute);if(d==0){int ca=check_assignment(line);if(ca<0)return 4;if(ca>0&&execute){const char*s=line;char name[128];parse_ident(&s,name,sizeof(name));s=skip(s)+1;int ok=0;Value v=eval_expr(&s,&ok);if(ok<=0)return 5;Sym*sym=find_sym(name);if(sym)sym->v=v;}else{int pr=run_print(line);if(pr==-2)return 5;if(pr<0&&strncmp(line,"try ",4)==0){/* exception syntax intentionally outside C Core subset */return 6;}if(pr<0)return 3;}}else if(d<0)return d==-2?5:3;}
line=strtok(NULL,"\n");}return 0;}
static char* read_all(const char*path,size_t*n){FILE*f=fopen(path,"rb");if(!f)return NULL;if(fseek(f,0,SEEK_END)){fclose(f);return NULL;}long z=ftell(f);rewind(f);char*b=(char*)malloc((size_t)z+1);if(!b){fclose(f);return NULL;}size_t r=fread(b,1,(size_t)z,f);fclose(f);b[r]=0;*n=r;return b;}
int main(int argc,char**argv){if(argc!=3||(strcmp(argv[1],"run")&&strcmp(argv[1],"check"))){fprintf(stderr,"usage: saga-c-core <run|check> file.saga\n");return 64;}size_t n=0;char*src=read_all(argv[2],&n);if(!src){fprintf(stderr,"cannot read %s: %s\n",argv[2],strerror(errno));return 66;}if(!lexical_profile((unsigned char*)src,n)){fprintf(stderr,"%s lexical profile violation\n",diag_id);free(src);return 2;}int execute=strcmp(argv[1],"run")==0;int rc=run_source(src,execute);if(rc&&diag_id)fprintf(stderr,"%s conformance diagnostic\n",diag_id);free(src);return rc;}
