from __future__ import annotations
import unicodedata as ud
from pathlib import Path

if ud.unidata_version != '15.1.0':
    raise SystemExit(f'Unicode 15.1.0 required, got {ud.unidata_version}')

def ranges(points):
    out=[]
    start=prev=None
    for cp in points:
        if start is None: start=prev=cp
        elif cp==prev+1: prev=cp
        else: out.append((start,prev)); start=prev=cp
    if start is not None: out.append((start,prev))
    return out

start_points=[]; cont_points=[]
for cp in range(0x110000):
    c=chr(cp)
    if c=='_' or c.isidentifier(): start_points.append(cp)
    if c=='_' or ('A'+c).isidentifier(): cont_points.append(cp)

# Canonical decomposition entries, CCC entries and valid composition pairs.
decomp={}
ccc={}
for cp in range(0x110000):
    c=chr(cp)
    cc=ud.combining(c)
    if cc: ccc[cp]=cc
    raw=ud.decomposition(c)
    if raw and not raw.startswith('<'):
        seq=tuple(int(x,16) for x in raw.split())
        decomp[cp]=seq
compose={}
for cp,seq in decomp.items():
    if len(seq)==2:
        s=''.join(map(chr,seq))
        n=ud.normalize('NFC',s)
        if len(n)==1 and ord(n)==cp:
            compose[seq]=cp

out=[]
out.append('// Code generated by tools/generate_unicode_go.py; DO NOT EDIT.')
out.append('// Unicode version: 15.1.0')
out.append('package main\n')
out.append('type runeRange struct { lo, hi rune }')
out.append('var xidStartRanges = []runeRange{')
for a,b in ranges(start_points): out.append(f'{{0x{a:X},0x{b:X}}},')
out.append('}')
out.append('var xidContinueRanges = []runeRange{')
for a,b in ranges(cont_points): out.append(f'{{0x{a:X},0x{b:X}}},')
out.append('}')
out.append('var canonicalDecomp = map[rune][]rune{')
for cp,seq in sorted(decomp.items()): out.append(f'0x{cp:X}:{{'+','.join(f'0x{x:X}' for x in seq)+'},')
out.append('}')
out.append('var combiningClass = map[rune]uint8{')
for cp,cc in sorted(ccc.items()): out.append(f'0x{cp:X}:{cc},')
out.append('}')
out.append('var canonicalCompose = map[[2]rune]rune{')
for (a,b),cp in sorted(compose.items()): out.append(f'{{0x{a:X},0x{b:X}}}:0x{cp:X},')
out.append('}')
Path('implementations/go/cmd/saga-go/unicode15_1.go').write_text('\n'.join(out)+'\n')
print('ranges',len(ranges(start_points)),len(ranges(cont_points)),'decomp',len(decomp),'ccc',len(ccc),'compose',len(compose))
